name: CI

on:
  push:
  #schedule:
  #  - cron: 0 0/4 * * *

jobs:
  pre-build:
    runs-on: ubuntu-latest
    name: The simplest jepsen test for HStreamDB
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Prepare environment for test
        run: |
          cd ./docker
          ./init-secret.sh

      - name: Start test cluster & run jepsen test
        run: |
          docker-compose --file ./docker/docker-compose.yml --compatibility -p jepsen up --build --abort-on-container-exit --exit-code-from control

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: jepsen-test-result
          path: |
            store/HStream
            !store/HStream/latest
          retention-days: 7
